name: Publish & Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        name: Publish & Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Publish
              run: cargo publish --verbose --all-features
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

            - name: Set Environment Variables
              run: |
                  echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
                  echo "NO_PREFIX_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

            - name: Create GitHub Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: https://crates.io/crates/bevy_doryen/${{ env.NO_PREFIX_VERSION }}
                  draft: false
                  prerelease: false
